### ISSUE TITLE
pyglet example needs instructions for how to properly build it

### ISSUE THREAD

**Issue by tigercoding56** [pygame-web/showroom#3]
there is no documentation (that a normal user is easily able to find) 
that details if there are any specific steps you need to take to get the pyglet demo in /src working   but when they try and run it via pygbag (and default instructions provided in pygbag readme)   it could be a bit confusing  
also idk how to build it properly since lack of docs so i cannot make PR for wiki)

https://github.com/pygame-web/showroom/assets/90169211/c36c4fbd-62f3-43a3-add4-69935bba9ab3

**Comment by pmp-p** [comment]
Normal user use Pygame-ce, that is what pygbag was made for. Panda3D has some decent support but there are still bleeding edges.

Everything else is experimental and up to **community for support**.
porting package can be very hard and (is) rewardless.

if you have problem with pyglet on WebAssembly just open an issue by them thank you ( unless there's one already open of couse like " Run pyglet in a web browser #949 " )

Please don't bother more on pyglet. It is now marked unsupported and wontfix.

**Comment by tigercoding56** [comment]
> Normal user use Pygame-ce, that is what pygbag was made for. Panda3D has some decent support but there are still bleeding edges.
> 
> Everything else is experimental and up to **community for support**. porting package can be very hard and (is) rewardless.
> 
> if you have problem with pyglet on WebAssembly just open an issue by them thank you ( unless there's one already open of couse like " Run pyglet in a web browser #949 " )
> 
> Please don't bother more on pyglet. It is now marked unsupported and wontfix.

ok   i saw  a comment linking to this  on a pyglet issue for pyglet-web so  i thought maybe it is still supported

**Comment by tigercoding56** [comment]
update   
`def notify(self,*args,**kwargs):
    pass
pyglet.app.base.threading.Condition.notify=notify`
kinda solves it  but no events fire now ...
